[package]
authors = ["stone <335612970@qq.com>"]
edition = "2018"
name = "growing-project"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
restaurant = {path = "./restaurant"}
rand = "0.5"
